services:
  languagetool:
    image: silviof/docker-languagetool
    expose:
      - "8010"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8010/v2/languages || exit 1"]
      interval: 2s
      retries: 15

  migrate:
    build: ./mdnt_app
    volumes:
      - db_data:/mdnt_app/db
      - media:/mdnt_app/media
    env_file:
      - .env
    environment:
      LANGUAGE_TOOL_HOST: http://languagetool:8010
    command: python manage.py migrate
    depends_on:
      languagetool:
          condition: service_healthy
    expose:
      - "8080"

  web:
    build:
      context: ./mdnt_app
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    env_file:
      - .env
    environment:
      LANGUAGE_TOOL_HOST: http://languagetool:8010
    volumes:
      - db_data:/mdnt_app/db
      - media:/mdnt_app/media
    expose:
      - "8000"
    depends_on:
      migrate:
          condition: service_completed_successfully
      languagetool:
          condition: service_healthy

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

volumes:
  db_data:
  media: